In [3]:
from sklearn.metrics.pairwise import cosine_similarity

import pandas as pd

import numpy as np 

print(123213213)

123213213


In [4]:
vector_df = pd.read_csv('/home/hamish/Downloads/word_vectors.csv', index_col=0 )

print(vector_df.head())

print(1)

                 0         1         2         3         4         5  \
ï        -0.014292  0.007838 -0.002896  0.007041  0.009640  0.000983   
»        -0.019124  0.004895  0.000261 -0.002996  0.004262  0.007593   
¿        -0.015925  0.008959  0.012728  0.001627  0.009002 -0.009196   
''        0.242879 -0.357776 -1.036951  0.469952 -1.611660 -0.920393   
proyecto  0.006645  0.002655 -0.002004  0.011898  0.009993 -0.003337   

                 6         7         8         9  ...        90        91  \
ï         0.005310  0.001771  0.005891  0.012021  ... -0.001305 -0.001553   
»        -0.008057  0.016138  0.009148  0.013248  ... -0.004555  0.008343   
¿         0.000113  0.014790  0.001011  0.016847  ...  0.005379 -0.000023   
''       -1.047843  0.812955  0.077639  0.406976  ...  0.014267 -0.450508   
proyecto -0.017918  0.001710  0.001841  0.021023  ...  0.001581  0.004362   

                92        93        94        95        96        97  \
ï        -0.014225  0.002071 -0.

In [5]:
similarity = cosine_similarity(vector_df.head(5))

#similarity.type()

In [7]:
print(similarity)

[[1.         0.87995355 0.88515484 0.52482921 0.75178471]
 [0.87995355 1.         0.8442184  0.5153964  0.75806   ]
 [0.88515484 0.8442184  1.         0.45465187 0.68961359]
 [0.52482921 0.5153964  0.45465187 1.         0.60301397]
 [0.75178471 0.75806    0.68961359 0.60301397 1.        ]]


In [8]:
a = 4
print(a)
print(1)



4
1
